# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

height_matrix = np.array(height)
weight_matrix = np.array(weight)

print(weight_matrix / (height_matrix**2) * 730)



[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [22]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
def makeMatrix(low,high,shape,data_type = 'int32'):
    if data_type == 'int32':
        convert_to = np.int32
    elif data_type == 'int64':
        convert_to = np.int64
    elif data_type == 'float32':
        convert_to = np.float32
    elif data_type == 'float64':
        convert_to = np.float64
    
    return np.random.uniform(low, high, shape).astype(convert_to)

print(makeMatrix(2, 100, (3,3), 'int32'))

[[74 83 92]
 [85 65 21]
 [ 7 27 42]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [28]:
import csv
import numpy as np

In [42]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on
def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

rs_2017 = load_data('redsox_2017_hitting.txt')
rs_2018 = load_data('redsox_2018_hitting.txt')

slg_2017 = rs_2017['SLG']
ab_2017 = rs_2017['AB']

slg_2018 = rs_2018['SLG']
ab_2018 = rs_2018['AB']

total_run_points_2017 = slg_2017 * ab_2017
overall_team_slg_2017 = sum(total_run_points_2017) / sum(ab_2017)

total_run_points_2018 = slg_2018 * ab_2018
overall_team_slg_2018 = sum(total_run_points_2018) / sum(ab_2018)

if overall_team_slg_2017 > overall_team_slg_2018:
    print(f'Boston Red Sox had a higher overall SLG in 2017 than in 2018.')
    print(f'In 2017 the team as a whole had a SLG of {overall_team_slg_2017:.3f}, while in 2018 it was only {overall_team_slg_2018:.3f}.')
else:
    print(f'Boston Red Sox had a higher overall SLG in 2018 than in 2017.')
    print(f'In 2018 the team as a whole had a SLG of {overall_team_slg_2018:.3f}, while in 2017 it was only {overall_team_slg_2017:.3f}.')



Boston Red Sox had a higher overall SLG in 2018 than in 2017.
In 2018 the team as a whole had a SLG of 0.454, while in 2017 it was only 0.408.
